# Generated by Django 6.1.1 on 2026-09-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_xa', models.CharField(max_length=50, unique=True, verbose_name='Mã Xã')),
                ('ten_xa', models.CharField(max_length=255, verbose_name='Tên Xã/Phường')),
                ('ma_huyen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã Huyện')),
                ('ten_huyen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Quận/Huyện')),
                ('geometry', models.JSONField(verbose_name='Geometry (GeoJSON)')),
            ],
        ),
        migrations.CreateModel(
            name='GEEDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('LANDSAT/LC08/C02/T1_TOA', 'Landsat 8 TOA'), ('COPERNICUS/S2_SR_HARMONIZED', 'Sentinel-2 SR')], max_length=100, verbose_name='Loại Dữ Liệu')),
                ('start_date', models.DateField(verbose_name='Từ Ngày')),
                ('end_date', models.DateField(verbose_name='Đến Ngày')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian yêu cầu')),
                ('download_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Tải GEE')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='Trạng Thái')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='gee_app.ward', verbose_name='Khu Vực')),
            ],
        ),
    ]
