# Generated by Django 6.1.1 on 2026-09-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gee_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='ma_huyen',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='ten_huyen',
        ),
    ]
