# Generated by Django 6.1.1 on 2026-09-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_app', '0002_remove_ward_ma_huyen_remove_ward_ten_huyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='geedatarequest',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive File ID'),
        ),
        migrations.AddField(
            model_name='geedatarequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GEE Task ID'),
        ),
    ]
