# Generated by Django 6.1.1 on 2026-09-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_app', '0003_geedatarequest_drive_file_id_geedatarequest_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geedatarequest',
            name='ndbi_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='NDBI Trung bình'),
        ),
        migrations.AddField(
            model_name='geedatarequest',
            name='ndvi_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='NDVI Trung bình'),
        ),
        migrations.AddField(
            model_name='geedatarequest',
            name='ndwi_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='NDWI Trung bình'),
        ),
    ]
