# Generated by Django 6.1.1 on 2026-09-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_app', '0004_geedatarequest_ndbi_mean_geedatarequest_ndvi_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geedatarequest',
            name='csv_download_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Tải CSV Chỉ Số'),
        ),
    ]
