# Generated by Django 6.1.1 on 2026-09-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_app', '0005_geedatarequest_csv_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='geedatarequest',
            name='dem_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ Cao Trung bình (m)'),
        ),
        migrations.AddField(
            model_name='geedatarequest',
            name='lst_mean',
            field=models.FloatField(blank=True, null=True, verbose_name='Nhiệt Độ Trung bình (°C)'),
        ),
        migrations.AlterField(
            model_name='geedatarequest',
            name='dataset',
            field=models.CharField(choices=[('LANDSAT/LC08/C02/T1_TOA', 'Landsat 8 TOA'), ('COPERNICUS/S2_SR_HARMONIZED', 'Sentinel-2 SR'), ('SRTM_DEM', 'Mô Hình Độ Cao (SRTM DEM 30m)'), ('L8_LST', 'Nhiệt Độ Bề Mặt (Landsat 8 LST)')], max_length=100, verbose_name='Loại Dữ Liệu'),
        ),
    ]
