# Generated by Django 6.1 on 2026-10-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee_app', '0006_geedatarequest_dem_mean_geedatarequest_lst_mean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Nguồn')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Nguồn')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Chỉ Số')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Chỉ Số')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateField(verbose_name='Thời Gian')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Giá Trị')),
                ('index_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gee_app.indextype')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gee_app.dataorigin')),
                ('request_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='gee_app.geedatarequest')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='gee_app.ward')),
            ],
            options={
                'indexes': [models.Index(fields=['observation_time'], name='gee_app_obs_observa_5bdfb5_idx'), models.Index(fields=['index_type', 'origin', 'ward'], name='gee_app_obs_index_t_e645ec_idx')],
            },
        ),
    ]
